version: "3"
services:
  postgres:
    image: postgres:11
    networks:
      - hmpps
    container_name: hmpps-workload-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
networks:
  hmpps:
