version: "3"
services:
  postgres:
    image: postgres:11
    networks:
      - hmpps
    container_name: hmpps-allocations-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
  localstack:
    image: localstack/localstack:0.13.1
    networks:
      - hmpps
    container_name: hmpps-allocations-localstack
    ports:
      - "4566:4566"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  tier-service:
    image: quay.io/hmpps/hmpps-tier
    networks:
      - hmpps
    container_name: tier-service
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
networks:
  hmpps:
