apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hmpps-allocations-ingress
  labels:
    app.kubernetes.io/name: hmpps-allocations
    role: alert-rules
spec:
  groups:
    - name: hmpps-allocations-ingress
      rules:
        # 5xx responses (all 5xx except 504) — >=3 in 5m
        - alert: Ingress5xxErrorResponses
          expr: |
            sum by (ingress, exported_namespace) (
              increase(nginx_ingress_controller_requests{
                exported_namespace="workforce-management-prod",
                ingress=~"hmpps-allocations(-v1-2)?",
                status=~"5(0[0-3]|0[5-9]|[1-9][0-9])"
              }[5m])
            ) >= 3
          for: 1m
          labels:
            severity: warning
            service: hmpps-allocations
          annotations:
            summary: Ingress serving 5xx (excl. 504) responses.

        # 504 responses — any in last 5m
        - alert: Ingress504ErrorResponses
          expr: |
            sum by (ingress, exported_namespace) (
              increase(nginx_ingress_controller_requests{
                exported_namespace="workforce-management-prod",
                ingress=~"hmpps-allocations(-v1-2)?",
                status="504"
              }[5m])
            ) > 0
          for: 1m
          labels:
            severity: warning
            service: hmpps-allocations
          annotations:
            summary: Ingress serving 504 responses.

        # 5xx on /health specifically — sustained rate > 0.5 req/s over 5m
        - alert: Ingress5xxOnHealthEndpoint
          expr: |
            sum by (ingress, exported_namespace) (
              rate(nginx_ingress_controller_requests{
                exported_namespace="workforce-management-prod",
                ingress=~"hmpps-allocations(-v1-2)?",
                path=~"/health.*",
                status=~"5.."
              }[5m])
            ) > 0.5
          for: 5m
          labels:
            severity: warning
            service: hmpps-allocations
          annotations:
            summary: High rate of 5xx errors on /health.

        # 429 rate limiting — any in last 1m
        - alert: IngressRatelimitBlocking
          expr: |
            sum by (ingress, exported_namespace) (
              increase(nginx_ingress_controller_requests{
                exported_namespace="workforce-management-prod",
                ingress=~"hmpps-allocations(-v1-2)?",
                status="429"
              }[1m])
            ) > 0
          for: 1m
          labels:
            severity: warning
            service: hmpps-allocations
          annotations:
            summary: Ingress is rate limiting (429s).

        # ModSecurity blocking (default 406) — > 0.33 req/s over 1m
        - alert: IngressModSecurityBlocking
          expr: |
            sum by (ingress, exported_namespace) (
              rate(nginx_ingress_controller_requests{
                exported_namespace="workforce-management-prod",
                ingress=~"hmpps-allocations(-v1-2)?",
                status="406"
              }[1m])
            ) > 0.33
          for: 1m
          labels:
            severity: warning
            service: hmpps-allocations
          annotations:
            summary: ModSecurity is blocking requests.
