{{- if .Values.refresh_environment -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-refresh-script
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e

    echo "${DB_HOST}:5432:${DB_NAME}:${DB_USER}:${DB_PASS}" > ~/.pgpass
    echo "${DB_HOST_PREPROD}:5432:${DB_NAME_PREPROD}:${DB_USER_PREPROD}:${DB_PASS_PREPROD}" >> ~/.pgpass
    chmod 0600 ~/.pgpass

    set -x
    # Dump production data
    pg_dump --host="$DB_HOST" \
      --username="$DB_USER" \
      --on-conflict-do-nothing \
      --column-inserts \
      --data-only \
      --no-privileges \
      --verbose \
      --table public.unallocated_cases \
      --file=/tmp/db.dump \
      "$DB_NAME"

    # Restore production data to preprod
    pg_restore --host="$DB_HOST_PREPROD" \
      --username="$DB_USER_PREPROD" \
      "$DB_NAME_PREPROD" < /tmp/db.dump

    rm -v /tmp/db.dump
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-allocations-refresh-cronjob
spec:
  schedule: "0 23 14 4 *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 1200
      template:
        spec:
          {{- if .Values.serviceAccountName }}
          serviceAccountName: {{ .Values.serviceAccountName }}
          {{- end }}
          securityContext:
            runAsUser: 999
          containers:
            - name: hmpps-allocations-refresh
              image: "postgres:15"
              command:
                - /bin/entrypoint.sh
              volumeMounts:
                - name: db-refresh-script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
              env:
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: db-refresh-secret
                      key: database_name
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-refresh-secret
                      key: database_username
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: db-refresh-secret
                      key: database_password
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: db-refresh-secret
                      key: rds_instance_address
                - name: DB_NAME_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: rds-allocation-instance-output
                      key: database_name
                - name: DB_USER_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: rds-allocation-instance-output
                      key: database_username
                - name: DB_PASS_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: rds-allocation-instance-output
                      key: database_password
                - name: DB_HOST_PREPROD
                  valueFrom:
                    secretKeyRef:
                      name: rds-allocation-instance-output
                      key: rds_instance_address
          restartPolicy: "Never"
          volumes:
            - name: db-refresh-script
              configMap:
                name: db-refresh-script
                defaultMode: 0755
  {{- end }}