hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566

hmpps-tier:
  endpoint:
    url: http://localhost:8099
assessment:
  endpoint:
    url: http://localhost:8099
assess-risks-needs:
  endpoint:
    url: http://localhost:8099
