hmpps.sqs:
  provider: localstack
  queues:
    tiercalculationqueue:
      queueName: hmpps_tier_event_queue
      dlqName: hmpps_tier_event_dlq
      subscribeTopicId: hmppsdomaintopic
      subscribeFilter: '{"eventType":[ "TIER_CALCULATION_COMPLETE"] }'
    hmppsoffenderqueue:
      queueName: hmpps_offender_event_queue
      dlqName: hmpps_offender_event_dlq
      subscribeTopicId: hmppsoffendertopic
      subscribeFilter: '{"eventType":[ "SENTENCE_CHANGED"] }'
  topics:
    hmppsdomaintopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    hmppsoffendertopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

hmpps-tier:
  endpoint:
    url: http://localhost:8082

hmpps-probation-estate:
  endpoint:
    url: http://localhost:8099

oauth:
  endpoint.url: http://localhost:9090/auth

datasource:
  url: "jdbc:postgresql://${database.endpoint:localhost:5432}/${database.name:postgres}"