spring:
  datasource:
    url: 'jdbc:h2:mem:probation-allocation;MODE=PostgreSQL;'

hmpps.sqs:
  provider: localstack
  queues:
    hmppsdomainqueue:
      queueName: hmpps_domain_event_queue
      dlqName: hmpps_domain_event_dlq
      subscribeTopicId: hmppsdomaintopic
      subscribeFilter: '{"eventType":[ "ALLOCATION_REQUIRED"] }'
    tiercalculationqueue:
      queueName: hmpps_tier_event_queue
      dlqName: hmpps_tier_event_dlq
      subscribeTopicId: hmppsdomaintopic
      subscribeFilter: '{"eventType":[ "TIER_CALCULATION_COMPLETE"] }'
  topics:
    hmppsdomaintopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

community:
  endpoint:
    url: http://localhost:8092
hmpps-tier:
  endpoint:
    url: http://localhost:8082

