generic-service:
  nameOverride: hmpps-allocations

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-allocations
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-allocations-cert
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /crn/reprocess {
          deny all;
          return 401;
        }
        location /queue-admin/** {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  serviceAccountName: "workforce-management"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-allocations:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "AUTH_API_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "AUTH_API_CLIENT_SECRET"
    rds-allocation-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
    sqs-domain-events-secret:
      HMPPS_SQS_QUEUES_TIERCALCULATIONQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-events-dl-secret:
      HMPPS_SQS_QUEUES_TIERCALCULATIONQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-allocations-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-allocations-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-allocations
  alertSeverity: hmpps-tier
