---
# Per environment values which override defaults in hmpps-allocations/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-allocations.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
