---
# Per environment values which override defaults in hmpps-allocations/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-allocations-dev.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
