---
# Per environment values which override defaults in hmpps-allocations/values.yaml

queue_cronjob_schedule: "*/15 7-21 * * 1-5"
refresh_environment: "ALWAYS"
refresh_cronjob_schedule: "*/30 21 * * 1,2,3,4,5"

generic-service:

  ingress:
    host: hmpps-allocations-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier-preprod.hmpps.service.justice.gov.uk
    HMPPS_PROBATION_ESTATE_ENDPOINT_URL: https://hmpps-probation-estate-api-preprod.hmpps.service.justice.gov.uk
    WORKFORCE_ALLOCATIONS_TO_DELIUS_ENDPOINT_URL: https://workforce-allocations-to-delius-preprod.hmpps.service.justice.gov.uk
    ASSESSMENT_ENDPOINT_URL: https://offender-prprod.aks-live-1.studio-hosting.service.justice.gov.uk
    ASSESS_RISKS_NEEDS_ENDPOINT_URL: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    COMMUNITY_ENDPOINT_URL: https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io/secure
    HMPPS_SQS_USE_WEB_TOKEN: "true"
    AWS_DEFAULT_REGION: "eu-west-2"

  serviceAccountName: workforce-management

  namespace_secrets:
    sqs-domain-events-secret:
      HMPPS_SQS_QUEUES_TIERCALCULATIONQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-events-dl-secret:
      HMPPS_SQS_QUEUES_TIERCALCULATIONQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-allocations-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-allocations-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"

  scheduledDowntime:
    enabled: true

generic-prometheus-alerts:
  businessHoursOnly: true