---
# Per environment values which override defaults in hmpps-allocations/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-allocations-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    COMMUNITY_ENDPOINT_URL: https://community-api-secure.test.delius.probation.hmpps.dsd.io/secure
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
    ASSESSMENT_ENDPOINT_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk