---
# Per environment values which override defaults in hmpps-allocations/values.yaml

generic-service:

  ingress:
    host: hmpps-allocations.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier.hmpps.service.justice.gov.uk
    WORKFORCE_ALLOCATIONS_TO_DELIUS_ENDPOINT_URL: https://workforce-allocations-to-delius.hmpps.service.justice.gov.uk
    ASSESSMENT_ENDPOINT_URL: https://offender-prod.aks-live-1.studio-hosting.service.justice.gov.uk
    ASSESS_RISKS_NEEDS_ENDPOINT_URL: https://assess-risks-and-needs.hmpps.service.justice.gov.uk
    COMMUNITY_ENDPOINT_URL: https://community-api-secure.probation.service.justice.gov.uk/secure

generic-prometheus-alerts:
  sqsOldestAlertQueueNames:
    - "Digital-Prison-Services-prod-hmpps_allocations_offender_events_queue"
    - "manage-a-workforce-production-hmpps_allocation_domain_events_queue"
  sqsNumberAlertQueueNames:
    - "Digital-Prison-Services-prod-hmpps_allocations_offender_events_queue_dl"
    - "manage-a-workforce-production-hmpps_allocation_domain_events_dlq"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
  ingress5xxErrorWindowMinutes: 4